FROM php:8.5-apache AS php85
ENV APACHE_DOCUMENT_ROOT /var/www
ENV APACHE_LOG_DIR /var/www/log/apache

WORKDIR ${APACHE_DOCUMENT_ROOT}


COPY ./config/apache2/*.conf /etc/apache2/conf-enabled


#local config
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/


# Install Linux libraries.
RUN apt-get update && apt-get install -y \
    vim \
    git \
    unzip \
    libicu-dev \
    libpq-dev \
    libzip-dev \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libldap-common \
    libldap2-dev \
    ca-certificates


#apache
RUN set -eux; \
    a2enmod rewrite; \
    a2enmod headers; \
    a2enmod expires; \
    a2enmod autoindex

RUN install-php-extensions intl ldap gd gd xdebug mysqli pdo_mysql pdo_pgsql \
    zip soap opcache exif @composer

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gnupg curl apt-transport-https lsb-release unzip \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | http_proxy='' bash - \
    && http_proxy='' apt-get install -y nodejs \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*




RUN npm config set cafile=/etc/ssl/certs/ca-certificates.crt


## yarn
RUN npm install --global yarn \
    && yarn config set cafile /etc/ssl/certs/ca-certificates.crt




#install phpstan
ENV PATH="$PATH:/root/.config/composer/vendor/bin"
RUN composer global require phpstan/phpstan





# Setup, Download & install Symfony CLI.
RUN set -eux; \
  curl -sS https://get.symfony.com/cli/installer | bash; \
  mv /root/.symfony5/bin/symfony /usr/bin
